import type { Metadata } from "next";

import { buildReportMetadata } from "@/lib/report-seo";
import {
  canGenerateReportMetadata,
  isDemoReportId,
  loadReportForPublicMetadata,
} from "@/lib/report-seo-loader";
import { getRequestSiteUrl } from "@/lib/request-site-url";
import { buildPageMetadata } from "@/lib/seo";
import { isSupabaseConfigured } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";

type ReportLayoutProps = {
  children: React.ReactNode;
  params: Promise<{ id: string }>;
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;

  if (!canGenerateReportMetadata(id)) {
    return buildPageMetadata({
      title: "Report not found",
      description: "This report link is invalid or has expired.",
      path: `/report/${id}`,
      index: false,
    });
  }

  if (!isDemoReportId(id) && !isSupabaseConfigured()) {
    return buildPageMetadata({
      title: "UX Report",
      description: "UX clarity report generated by Klynt.",
      path: `/report/${id}`,
      index: false,
    });
  }

  try {
    const report = await loadReportForPublicMetadata(id);

    if (!report) {
      return buildPageMetadata({
        title: "UX Report",
        description: "UX clarity report generated by Klynt.",
        path: `/report/${id}`,
        index: false,
      });
    }

    return buildReportMetadata(id, report, getRequestSiteUrl());
  } catch {
    return buildPageMetadata({
      title: "UX Report",
      description: "UX clarity report generated by Klynt.",
      path: `/report/${id}`,
      index: false,
    });
  }
}

export default function ReportLayout({ children }: ReportLayoutProps) {
  return children;
}
