export function LandingHeroPattern() {
  return (
    <div
      className="pointer-events-none absolute inset-0 overflow-hidden"
      aria-hidden
    >
      <svg
        className="absolute inset-0 h-full w-full"
        viewBox="0 0 1440 900"
        preserveAspectRatio="xMidYMid slice"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <defs>
          <filter
            id="hero-motion-blur"
            x="-30%"
            y="-30%"
            width="160%"
            height="160%"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="36 0" />
          </filter>
          <filter
            id="hero-motion-blur-soft"
            x="-30%"
            y="-30%"
            width="160%"
            height="160%"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="22 0" />
          </filter>
        </defs>

        <g filter="url(#hero-motion-blur)">
          <rect
            x={-120}
            y={32}
            width={820}
            height={192}
            rx={4}
            fill="#D4F2FC"
            fillOpacity={0.42}
          />
          <rect
            x={520}
            y={152}
            width={1040}
            height={168}
            rx={4}
            fill="#FFFFFF"
            fillOpacity={0.2}
          />
          <rect
            x={-80}
            y={272}
            width={760}
            height={180}
            fill="#B8E8F8"
            fillOpacity={0.38}
          />
          <rect
            x={420}
            y={392}
            width={1120}
            height={204}
            rx={4}
            fill="#3AA8D8"
            fillOpacity={0.26}
          />
          <rect
            x={-100}
            y={528}
            width={680}
            height={162}
            fill="#E8F6FC"
            fillOpacity={0.34}
          />
          <rect
            x={640}
            y={648}
            width={920}
            height={186}
            rx={4}
            fill="#0B6FA0"
            fillOpacity={0.1}
          />
          <rect
            x={80}
            y={768}
            width={880}
            height={177}
            fill="#FFFFFF"
            fillOpacity={0.14}
          />
        </g>

        <g filter="url(#hero-motion-blur-soft)">
          <rect
            x={280}
            y={96}
            width={640}
            height={108}
            fill="#0F7FB3"
            fillOpacity={0.07}
          />
          <rect
            x={-60}
            y={448}
            width={520}
            height={96}
            fill="#061C2F"
            fillOpacity={0.04}
          />
          <rect
            x={900}
            y={688}
            width={620}
            height={120}
            fill="#D4F2FC"
            fillOpacity={0.22}
          />
        </g>
      </svg>
    </div>
  );
}
