import Link from "next/link";
import {
  LegalDocumentPage,
  LegalSection,
} from "@/components/LegalDocumentPage";

export default function TermsPage() {
  return (
    <LegalDocumentPage title="Terms of Service" lastUpdated="May 26, 2026">
      <LegalSection title="Agreement">
        <p>
          By accessing or using Klynt at klynt.one (&ldquo;Service&rdquo;), you
          agree to these Terms of Service. If you do not agree, do not use the
          Service.
        </p>
      </LegalSection>

      <LegalSection title="What Klynt provides">
        <p>
          Klynt analyzes publicly accessible web pages and generates automated
          UX clarity reports, including issues, improvement suggestions, and
          copy refinements. Output is generated by AI and is provided for
          informational purposes only — not as professional design, legal, or
          business advice.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Use the Service for unlawful purposes or to violate others&apos; rights</li>
          <li>Submit URLs or content you do not have permission to analyze</li>
          <li>Attempt to disrupt, overload, reverse engineer, or scrape the Service</li>
          <li>Misrepresent AI-generated reports as human expert audits without disclosure</li>
        </ul>
      </LegalSection>

      <LegalSection title="No warranty">
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available.&rdquo; We do not guarantee that reports will be accurate,
          complete, or suitable for any particular purpose. UX scores and impact
          estimates are approximations based on visible page content at the time
          of analysis.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <p>
          To the fullest extent permitted by law, Klynt and its operators will
          not be liable for any indirect, incidental, special, or consequential
          damages arising from your use of the Service, including lost profits,
          lost data, or business interruption.
        </p>
      </LegalSection>

      <LegalSection title="Intellectual property">
        <p>
          The Klynt brand, website, and software are owned by us or our
          licensors. You retain rights to content you submit. You grant us a
          limited license to process submitted URLs and related content solely
          to operate and improve the Service.
        </p>
      </LegalSection>

      <LegalSection title="Changes and availability">
        <p>
          We may modify, suspend, or discontinue features at any time. We may
          update these Terms by posting a revised version on this page. Material
          changes take effect when published unless stated otherwise.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          These Terms are governed by applicable law in the jurisdiction where
          Klynt operates, without regard to conflict-of-law principles. If any
          provision is unenforceable, the remaining provisions remain in effect.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these Terms? Contact us via the{" "}
          <Link href="/contact" className="font-medium text-[#2563EB] hover:underline">
            contact page
          </Link>
          .
        </p>
      </LegalSection>
    </LegalDocumentPage>
  );
}
